### PR TITLE
Blacklist system, 2nd branch

### PR DESCRIPTION
**Pull request by immjs**
This is my 2nd branch for a blacklist system.

### CODE REVIEW

**Comment by immjs** [comment]
These stupid code tidying rules...
Anyway, I passed through them.
Please ignore the "Functionnal blacklist system" pull request.

**Comment by immjs** [comment]
Took me a while but here we are!

**Comment by nobobo1234** [comment]
Please delete the txt file and delete the warning message after 5 seconds.

**Comment by immjs** [comment]
Aight!

**Comment by immjs** [comment]
Wait can I even bring changes on mobile?

**Comment by immjs** [comment]
Changes made!
But...
We won't be able to find warnings later on, unless we implement some DB thing.
But that will be for another pull request maybe.

**Comment by immjs** [comment]
YES! All passed through!

**Comment by immjs** [comment]
*also when I said changes made I was on the wrong branch 🤦

**Comment by nobobo1234** [comment]
What do you mean by the post-scriptum?

**Comment by immjs** [comment]
*It's a pre scriptum

**Comment by immjs** [comment]
I mean searching the mention via the discord message searching was the only way to find precedent warnings. Now that it's being deleted there is no way to look for precedent warnings. I propose to continue on the pseudorandom channel

**Pull request merged**
